#텐서 (tensor)이해하기

scalar -> vector -> matrix -> tensor

In [ ]:
import numpy as np

In [ ]:
#numpy는 숫자 데이터를 array화 시킬 수 있음
arr = np.array(5)
print(arr.shape)
#0차원!! 그래서 shape도 아무것도 없다,.

()


In [ ]:
arr.ndim #ndim number of dimension

0

##1차원

[]넣음

In [ ]:
arr = np.array([5])
#[]를 씌워 리스ㅌ화 시키면 차원이생기
print(arr.shape)#shape를 표현할 때 차원때문에 (1,)이런식으로 표현하게 된다. ,당 차원 하나
print(arr.ndim)

(1,)
1


In [ ]:
arr = np.array([1,2,3])
print(arr.shape)#세개있다

(3,)


##2차원

[[]]넣음

In [ ]:
arr = np.array([[1,2,3]])
print(arr.shape)

(1, 3)


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

(3, 3)


#numpy 기초

In [ ]:
#zeros & one

zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones([10,10])
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.arange(5)#0부터 5개
arr


array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(4,9)#4이상 9미만
arr

array([4, 5, 6, 7, 8])

In [ ]:
arr = np.arange(9).reshape(3,3)#arange는 무조건 1차원이라서 차원수를 바꾸려면 reshape사용
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#index
arr[1][2]

5

In [ ]:
arr[1,2]#이렇게해도 쌉가능!!!

5

In [ ]:
#slicing
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
#boolean indexing
data = np.random.randn(3,3)
data

array([[-1.56418425,  0.765381  ,  0.05751146],
       [ 1.60449987,  0.34313802, -0.92135501],
       [-0.07739604,  0.89393604, -0.47474362]])

In [ ]:
print(data <= 0)
data[data<=0] = 1
print(data)

[[ True False False]
 [False False  True]
 [ True False  True]]
[[1.         0.765381   0.05751146]
 [1.60449987 0.34313802 1.        ]
 [1.         0.89393604 1.        ]]


In [ ]:
#broadcast
#broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,
#한쪽의 차원이라도 같거나 값으 개수가 하나일 때 여러 복사를 하여 연산
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr *3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
arr +  np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [ ]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.add(arr,1)
arr +1 #똑같다

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.random.randint(2,size = 27).reshape(3,3,3)
arr_2 = np.random.randint(2, size = 9).reshape(3,3)

In [ ]:
arr.shape

(3, 3, 3)

In [ ]:
arr + arr_2 #같으면 arr_2의 값들이 3개 복사되어 더하게 된다.

array([[[0, 1, 0],
        [0, 2, 1],
        [0, 1, 1]],

       [[1, 0, 0],
        [1, 1, 2],
        [0, 1, 0]],

       [[0, 1, 1],
        [1, 1, 2],
        [1, 1, 0]]])

In [ ]:
np.sum(arr) 

11

In [ ]:
np.max(arr)

1

In [ ]:
np.max(arr + arr_2, 0)#0차원에서 가장 큰 값을 반환

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
np.sum(arr + arr_2, 0)#0차원 끼리의 합

array([[1, 2, 1],
       [2, 4, 5],
       [1, 3, 1]])

In [ ]:
arr + arr_2

array([[[0, 1, 0],
        [0, 2, 1],
        [0, 1, 1]],

       [[1, 0, 0],
        [1, 1, 2],
        [0, 1, 0]],

       [[0, 1, 1],
        [1, 1, 2],
        [1, 1, 0]]])

In [ ]:
np.sum(arr + arr_2, -1)#요건 가장 마지막 차원 수준으 ㅣ합

array([[1, 3, 2],
       [1, 4, 1],
       [2, 4, 2]])

In [ ]:
arr = np.array([1,56,6,2,67,23])
arr

array([ 1, 56,  6,  2, 67, 23])

In [ ]:
np.argmax(arr)#4번째꺼가 가장 크다
print(arr[np.argmax(arr)])

67


In [ ]:
np.unique(arr)#유일값만 반환하는거.

array([ 1,  2,  6, 23, 56, 67])

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[1,2,3]])

In [3]:
arr.dtype#알아서 잡아준다.

dtype('int64')

In [6]:
arr = arr.astype('int8')#이렇게 바꿔줄 수 있다.
arr.dtype

dtype('int8')

In [7]:
arr_2 = np.array([[1,2,3],[1,2,3]], dtype = np.uint8)#이렇게 하면 처음에 넣어줄 수 있다.
arr_2.dtype

dtype('uint8')

In [12]:
print(len(arr.shape))#으로 차우너 확인 가능
print(arr.size)#으로 사이즈 확인가능

2
6


In [13]:
#reshape

arr.shape

(2, 3)

In [16]:
arr = arr.reshape([1,6])#사이즈는 유지하고 모양만 바꾼다.
arr.shape

(1, 6)

In [17]:
arr = np.array([[1,2,3],[1,2,3]])
arr.reshape([6]).shape

(6,)

In [23]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [24]:
arr = arr.reshape(1,-1)#1하고 남는거
arr.shape

(1, 6)

In [26]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [27]:
arr = arr.reshape([32,2])
arr.shape 

(32, 2)

In [32]:
arr = arr.reshape(-1,2,1,1,1,1)
arr.shape

(32, 2, 1, 1, 1, 1)

In [33]:
arr

array([[[[[[ 0.59183029]]]],



        [[[[ 1.8477694 ]]]]],




       [[[[[-1.24106373]]]],



        [[[[ 0.52788072]]]]],




       [[[[[ 0.25614411]]]],



        [[[[ 1.71496162]]]]],




       [[[[[-1.1318196 ]]]],



        [[[[-0.15669627]]]]],




       [[[[[ 1.25686646]]]],



        [[[[-0.8767588 ]]]]],




       [[[[[-0.74355714]]]],



        [[[[-1.81466766]]]]],




       [[[[[ 0.19600707]]]],



        [[[[ 0.12202163]]]]],




       [[[[[ 2.26860099]]]],



        [[[[ 0.41720378]]]]],




       [[[[[-1.0122326 ]]]],



        [[[[-1.12930987]]]]],




       [[[[[ 0.21517901]]]],



        [[[[ 0.97299533]]]]],




       [[[[[ 0.40328307]]]],



        [[[[-0.9896878 ]]]]],




       [[[[[-1.22438293]]]],



        [[[[ 1.07621355]]]]],




       [[[[[-0.79646716]]]],



        [[[[-1.02240195]]]]],




       [[[[[-0.66146644]]]],



        [[[[ 1.02892151]]]]],




       [[[[[ 0.03443517]]]],



        [[[[-0.20004273]]]]],




       [[[

In [34]:
#ravel은 arr의 차원을 1로 바꿔줌
arr.shape

(32, 2, 1, 1, 1, 1)

In [45]:
arr = arr.ravel()# arr = arr.reshape(-1)과 같다
arr.shape

(64,)

In [46]:
#np.expand_dims()
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [43]:
arr = arr.ravel()
arr.shape

(64,)

In [ ]:
arr = np.expand_dims(arr, -1)